/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.reporter.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractMeta implements Serializable {

    private static final long serialVersionUID = 901145374;

    private String        partyId;
    private String        contractId;
    private LocalDateTime wtime;
    private Long          lastEventId;
    private Integer       scheduleId;
    private Integer       calendarId;
    private LocalDateTime lastReportCreatedAt;

    public ContractMeta() {}

    public ContractMeta(ContractMeta value) {
        this.partyId = value.partyId;
        this.contractId = value.contractId;
        this.wtime = value.wtime;
        this.lastEventId = value.lastEventId;
        this.scheduleId = value.scheduleId;
        this.calendarId = value.calendarId;
        this.lastReportCreatedAt = value.lastReportCreatedAt;
    }

    public ContractMeta(
        String        partyId,
        String        contractId,
        LocalDateTime wtime,
        Long          lastEventId,
        Integer       scheduleId,
        Integer       calendarId,
        LocalDateTime lastReportCreatedAt
    ) {
        this.partyId = partyId;
        this.contractId = contractId;
        this.wtime = wtime;
        this.lastEventId = lastEventId;
        this.scheduleId = scheduleId;
        this.calendarId = calendarId;
        this.lastReportCreatedAt = lastReportCreatedAt;
    }

    public String getPartyId() {
        return this.partyId;
    }

    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

    public String getContractId() {
        return this.contractId;
    }

    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    public LocalDateTime getWtime() {
        return this.wtime;
    }

    public void setWtime(LocalDateTime wtime) {
        this.wtime = wtime;
    }

    public Long getLastEventId() {
        return this.lastEventId;
    }

    public void setLastEventId(Long lastEventId) {
        this.lastEventId = lastEventId;
    }

    public Integer getScheduleId() {
        return this.scheduleId;
    }

    public void setScheduleId(Integer scheduleId) {
        this.scheduleId = scheduleId;
    }

    public Integer getCalendarId() {
        return this.calendarId;
    }

    public void setCalendarId(Integer calendarId) {
        this.calendarId = calendarId;
    }

    public LocalDateTime getLastReportCreatedAt() {
        return this.lastReportCreatedAt;
    }

    public void setLastReportCreatedAt(LocalDateTime lastReportCreatedAt) {
        this.lastReportCreatedAt = lastReportCreatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ContractMeta other = (ContractMeta) obj;
        if (partyId == null) {
            if (other.partyId != null)
                return false;
        }
        else if (!partyId.equals(other.partyId))
            return false;
        if (contractId == null) {
            if (other.contractId != null)
                return false;
        }
        else if (!contractId.equals(other.contractId))
            return false;
        if (wtime == null) {
            if (other.wtime != null)
                return false;
        }
        else if (!wtime.equals(other.wtime))
            return false;
        if (lastEventId == null) {
            if (other.lastEventId != null)
                return false;
        }
        else if (!lastEventId.equals(other.lastEventId))
            return false;
        if (scheduleId == null) {
            if (other.scheduleId != null)
                return false;
        }
        else if (!scheduleId.equals(other.scheduleId))
            return false;
        if (calendarId == null) {
            if (other.calendarId != null)
                return false;
        }
        else if (!calendarId.equals(other.calendarId))
            return false;
        if (lastReportCreatedAt == null) {
            if (other.lastReportCreatedAt != null)
                return false;
        }
        else if (!lastReportCreatedAt.equals(other.lastReportCreatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.partyId == null) ? 0 : this.partyId.hashCode());
        result = prime * result + ((this.contractId == null) ? 0 : this.contractId.hashCode());
        result = prime * result + ((this.wtime == null) ? 0 : this.wtime.hashCode());
        result = prime * result + ((this.lastEventId == null) ? 0 : this.lastEventId.hashCode());
        result = prime * result + ((this.scheduleId == null) ? 0 : this.scheduleId.hashCode());
        result = prime * result + ((this.calendarId == null) ? 0 : this.calendarId.hashCode());
        result = prime * result + ((this.lastReportCreatedAt == null) ? 0 : this.lastReportCreatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ContractMeta (");

        sb.append(partyId);
        sb.append(", ").append(contractId);
        sb.append(", ").append(wtime);
        sb.append(", ").append(lastEventId);
        sb.append(", ").append(scheduleId);
        sb.append(", ").append(calendarId);
        sb.append(", ").append(lastReportCreatedAt);

        sb.append(")");
        return sb.toString();
    }
}
