version: '3'
services:
  postgresql:
    image: postgres:9.6
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reporter
