server:
  port: @server.port@
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      maximum-pool-size: 3
      idle-timeout: 30000
  output:
    ansi:
      enabled: always
jobs:
  synchronization:
    enabled: false
  report:
    enabled: false
kafka:
  bootstrap:
    servers: localhost:9092
  concurrency: 1
  processing:
    payout:
      topic: mg-payout-100-2
      enabled: false
    payment:
      topic: mg-invoice-100-2
      enabled: false
  ssl:
    enabled: false
    keystore-location: src/main/resources/cert/kenny-k.struzhkin.p12
    keystore-password: kenny
    key-password: kenny
    server-password: kenny12
    server-keystore-location: src/main/resources/cert/truststore.p12
report:
  defaultTimeZone: Europe/Moscow
  batchSize: 1
retry-policy:
  maxAttempts: -1
partyManagement:
  url: http://hellgate:8022/v1/processing/partymgmt
  timeout: 5000
bustermaze:
  payout:
    polling:
      url: http://localhost:8026/repo/payout
      housekeeperTimeout: 15000
      maxPoolSize: 1
      maxQuerySize: 1000
      delay: 10000
      retryDelay: 1000
      enabled: false
domainConfig:
  url: http://dominant:8022/v1/domain/repository
  timeout: 5000
filestorage:
  url: http://file-storage:8022/file_storage
  clientTimeout: 5000
  urlLifeTimeDuration: 360
  timeZone: Europe/Moscow
reporting:
  reportsLimit: 0
  defaultTimeZone: Europe/Moscow
