info:
  version: @project.version@
  stage: dev
  single-instance-mode: false
server:
  port: '@server.port@'
management:
  security:
    flag: false
  server:
    port: @management.port@
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 3
  flyway:
    schemas: @db.schema@
    table: schema_version
  quartz:
    job-store-type: JDBC
    properties:
      org.quartz:
        jobStore:
          class: org.quartz.impl.jdbcjobstore.JobStoreTX
          driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
          isClustered: true
          misfireThreshold: 60000
          useProperties: true
        plugin:
          shutdownHook:
            class: org.quartz.plugins.management.ShutdownHookPlugin
            cleanShutdown: false
        scheduler:
          instanceId: AUTO
          instanceName: reporter-scheduler
        threadPool:
          makeThreadsDaemons: true
          threadNamePrefix: Scheduler
    jdbc:
      initialize-schema: ALWAYS
  output:
    ansi:
      enabled: ALWAYS
  task:
    scheduling:
      pool:
        size: 10

kafka:
  bootstrap-servers: localhost:9092
  client-id: reporter
  ssl:
    enabled: false
    trust-store-location: "test"
    trust-store-password: "test"
    key-store-location: "test"
    key-store-password: "test"
    key-password: "test"
    key-store-type: PKCS12
    trust-store-type: PKCS12
  consumer:
    group-id: "ReporterListener"
    enable-auto-commit: false
    auto-offset-reset: earliest
    max-poll-records: 20
    max-poll-interval-ms: 30000
    session-timeout-ms: 30000
    party-management:
      concurrency: 5
  topics:
    party-management:
      id: mg-events-party
      enabled: false
      concurrency: 1
    invoicing:
      id: mg-invoice-100-2
      enabled: false
      concurrency: 1
      throttling-timeout-ms: 50
      error-throttling-timeout-ms: 1000

aggregation:
  enabled: false
  invoicing:
    timeout: 900000
  balancees:
    timeout: 900000

payouter:
  polling:
    url: http://payouter:8022/repo
    housekeeperTimeout: 15000
    maxQuerySize: 1000
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
    enabled: false

hellgate:
  invoicing:
    url: http://localhost:8023/v1/invoicing
    timeout: 30000

partyManagement:
  url: http://hellgate:8022/v1/processing/partymgmt
  timeout: 5000

magista:
  url: http://magista:8022/stat
  timeout: 60000

signer:
  url: http://signer:8022/signer
  timeout: 5000

domainConfig:
  url: http://dominant:8022/v1/domain/repository
  timeout: 5000

report:
  defaultTimeZone: Europe/Moscow
  batchSize: 1
  includeAdjustments: false

storage:
  endpoint: localhost:42827
  signingRegion: RU
  bucketName: test
  client:
    maxErrorRetry: 10
  accessKey: test
  secretKey: test
  clientProtocol: HTTP

retry-policy:
  maxAttempts: 5
