server:
  port: @server.port@
partyManagement:
  url: http://hellgate:8022/v1/processing/partymgmt
magista:
  url: http://magista:8022/stat
  timeout: 60000
signer:
  url: http://signer:8022/signer
domainConfig:
  url: http://dominant:8022/v1/domain/repository
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      maximum-pool-size: 3
      idle-timeout: 30000
report:
  defaultTimeZone: Europe/Moscow
  needSign: true
storage:
  endpoint: localhost
  signingRegion: RU
  bucketName: "reports"
  client:
    maxErrorRetry: 10

