info:
  version: @project.version@
  stage: dev
server:
  port: @server.port@
management:
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
  security:
    flag: false
spring:
  application:
    name: @project.name@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 3
  flyway:
    schemas: @db.schema@
  output:
    ansi:
      enabled: always
partyManagement:
  url: http://hellgate:8022/v1/processing/partymgmt
  timeout: 5000
magista:
  url: http://magista:8022/stat
  timeout: 60000
bustermaze:
  url: http://bustermaze:8022/repo
  polling:
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
    housekeeperTimeout: 15000
signer:
  url: http://signer:8022/signer
  timeout: 5000
domainConfig:
  url: http://dominant:8022/v1/domain/repository
  timeout: 5000
report:
  defaultTimeZone: Europe/Moscow
  batchSize: 1
storage:
  endpoint: localhost:42827
  signingRegion: RU
  bucketName: test
  client:
    maxErrorRetry: 10
  accessKey: test
  secretKey: test
  clientProtocol: HTTP
