server:
  port: @server.port@
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      maximum-pool-size: 3
      idle-timeout: 30000
  output:
    ansi:
      enabled: always
management:
  security:
    enabled: false
jobs:
  synchronization:
    enabled: false
  report:
    enabled: false
kafka:
  bootstrap:
    servers: localhost:9092
  processing:
    payout:
      topic: mg-payout-100-2
      enabled: false
    payment:
      topic: mg-invoice-100-2
      enabled: false
  concurrency: 1
  max-pool-records: 300
  fetch-min-bytes: 1024
  fetch-max-wait-ms: 1000
  ssl:
    enabled: false
    truststore:
      location-config: "src/main/resources/cert/truststore.p12"
      password-config: "kenny12"
    keystore:
      location-config: "src/main/resources/cert/keystore.p12"
      password-config: "kenny"
    key:
      password-config: "kenny"
report:
  defaultTimeZone: Europe/Moscow
  batchSize: 1
storage:
  endpoint: localhost:42827
  signingRegion: RU
  bucketName: test
  client:
    maxErrorRetry: 10
  accessKey: test
  secretKey: test
  clientProtocol: HTTP
retry-policy:
  maxAttempts: -1
partyManagement:
  url: http://hellgate:8022/v1/processing/partymgmt
  timeout: 5000
bustermaze:
  payout:
    polling:
      url: http://localhost:8026/repo/payout
      housekeeperTimeout: 15000
      maxPoolSize: 1
      maxQuerySize: 1000
      delay: 10000
      retryDelay: 1000
      enabled: false
domainConfig:
  url: http://dominant:8022/v1/domain/repository
  timeout: 5000
