server:
  port: @server.port@
partyManagement:
  url: http://hellgate:8022/v1/processing/partymgmt
  timeout: 5000
magista:
  url: http://magista:8022/stat
  timeout: 60000
bustermaze:
  url: http://bustermaze:8022/repo
  polling:
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
    housekeeperTimeout: 15000
signer:
  url: http://signer:8022/signer
  timeout: 5000
domainConfig:
  url: http://dominant:8022/v1/domain/repository
  timeout: 5000
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      maximum-pool-size: 3
      idle-timeout: 30000
report:
  defaultTimeZone: Europe/Moscow
storage:
  endpoint: localhost
  signingRegion: RU
  bucketName: "reports"
  client:
    maxErrorRetry: 10

