info:
  version: @project.version@
  stage: dev
  scheduler-pool-size: 5
  single-instance-mode: true
server:
  port: @server.port@
management:
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
  security:
    flag: false
spring:
  application:
    name: @project.name@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      data-source-properties:
        reWriteBatchedInserts: true
      idle-timeout: 30000
      maximum-pool-size: 3
  flyway:
    schemas: @db.schema@
  output:
    ansi:
      enabled: ALWAYS
---
cache:
  invoice:
    size: 10000
  payment:
    size: 10000
---
kafka:
  bootstrap-servers: localhost:9092
  client-id: reporter
  ssl:
    enabled: false
    trust-store-location: "test"
    trust-store-password: "test"
    key-store-location: "test"
    key-store-password: "test"
    key-password: "test"
    key-store-type: PKCS12
    trust-store-type: PKCS12
  consumer:
    concurrency: 8
    group-id: "ReporterListener"
    enable-auto-commit: false
    auto-offset-reset: earliest
    max-poll-records: 20
  topics:
    invoice:
      id: mg-invoice-100-2
---
report:
  defaultTimeZone: Europe/Moscow
  batchSize: 1
---
storage:
  endpoint: localhost:42827
  signingRegion: RU
  bucketName: test
  client:
    maxErrorRetry: 10
  accessKey: test
  secretKey: test
  clientProtocol: HTTP
---
partyManagement:
  url: http://hellgate:8022/v1/processing/partymgmt
  timeout: 5000
---
bustermaze:
  payout:
    polling:
      url: http://localhost:8026/repo/payout
      housekeeperTimeout: 15000
      maxPoolSize: 1
      maxQuerySize: 1000
      delay: 10000
      retryDelay: 1000
  payment:
    polling:
      url: http://localhost:8026/repo
      housekeeperTimeout: 15000
      maxPoolSize: 1
      maxQuerySize: 1000
      delay: 10000
      retryDelay: 1000
---
domainConfig:
  url: http://dominant:8022/v1/domain/repository
  timeout: 5000
