server:
  port: @server.port@
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      maximum-pool-size: 3
      idle-timeout: 30000
  output:
    ansi:
      enabled: always
jobs:
  synchronization:
    enabled: false
  report:
    enabled: false
kafka:
  bootstrap:
    servers: kenny-kafka1.bst1.rbkmoney.net:9092
  processing:
    topic: mg-invoice-100-2
  concurrency: 5
  ssl:
    enable: false
    keystore-location: "src/main/resources/cert/kenny-k.struzhkin.p12"
    keystore-password: "kenny"
    key-password: "kenny"
    server-password: "kenny12"
    server-keystore-location: "src/main/resources/cert/truststore.p12"
report:
  defaultTimeZone: Europe/Moscow
  batchSize: 1
storage:
  endpoint: localhost:42827
  signingRegion: RU
  bucketName: "test"
  client:
    maxErrorRetry: 10
  accessKey: "test"
  secretKey: "test"
  clientProtocol: "HTTP"
retry-policy:
  maxAttempts: -1
partyManagement:
  url: http://hellgate:8022/v1/processing/partymgmt
  timeout: 5000
bustermaze:
  processing:
    polling:
      url: http://localhost:8026/repo
      housekeeperTimeout: 15000
      maxPoolSize: 1
      maxQuerySize: 1000
      delay: 10000
      retryDelay: 1000
      enable: true
  payout:
    polling:
      url: http://localhost:8026/repo/payout
      housekeeperTimeout: 15000
      maxPoolSize: 1
      maxQuerySize: 1000
      delay: 10000
      retryDelay: 1000
      enable: true
signer:
  url: http://signer:8022/signer
  timeout: 5000
domainConfig:
  url: http://dominant:8022/v1/domain/repository
  timeout: 5000
