/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.reporter.domain.tables;


import com.rbkmoney.reporter.domain.Keys;
import com.rbkmoney.reporter.domain.Rpt;
import com.rbkmoney.reporter.domain.tables.records.FileRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class File extends TableImpl<FileRecord> {

    private static final long serialVersionUID = 397859060;

    /**
     * The reference instance of <code>rpt.file</code>
     */
    public static final File FILE = new File();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileRecord> getRecordType() {
        return FileRecord.class;
    }

    /**
     * The column <code>rpt.file.id</code>.
     */
    public final TableField<FileRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>rpt.file.report_id</code>.
     */
    public final TableField<FileRecord, Long> REPORT_ID = createField("report_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>rpt.file.bucket_id</code>.
     */
    public final TableField<FileRecord, String> BUCKET_ID = createField("bucket_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>rpt.file.filename</code>.
     */
    public final TableField<FileRecord, String> FILENAME = createField("filename", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>rpt.file.md5</code>.
     */
    public final TableField<FileRecord, String> MD5 = createField("md5", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>rpt.file.sha256</code>.
     */
    public final TableField<FileRecord, String> SHA256 = createField("sha256", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * Create a <code>rpt.file</code> table reference
     */
    public File() {
        this("file", null);
    }

    /**
     * Create an aliased <code>rpt.file</code> table reference
     */
    public File(String alias) {
        this(alias, FILE);
    }

    private File(String alias, Table<FileRecord> aliased) {
        this(alias, aliased, null);
    }

    private File(String alias, Table<FileRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Rpt.RPT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<FileRecord> getPrimaryKey() {
        return Keys.FILE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<FileRecord>> getKeys() {
        return Arrays.<UniqueKey<FileRecord>>asList(Keys.FILE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<FileRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<FileRecord, ?>>asList(Keys.FILE__FILE_REPORT_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public File as(String alias) {
        return new File(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public File rename(String name) {
        return new File(name, null);
    }
}
