/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.reporter.domain;


import com.rbkmoney.reporter.domain.tables.File;
import com.rbkmoney.reporter.domain.tables.Report;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rpt extends SchemaImpl {

    private static final long serialVersionUID = -864306690;

    /**
     * The reference instance of <code>rpt</code>
     */
    public static final Rpt RPT = new Rpt();

    /**
     * The table <code>rpt.file</code>.
     */
    public final File FILE = com.rbkmoney.reporter.domain.tables.File.FILE;

    /**
     * The table <code>rpt.report</code>.
     */
    public final Report REPORT = com.rbkmoney.reporter.domain.tables.Report.REPORT;

    /**
     * No further instances allowed
     */
    private Rpt() {
        super("rpt", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.REPORT_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            File.FILE,
            Report.REPORT);
    }
}
