/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.reporter.domain.tables.records;


import com.rbkmoney.reporter.domain.tables.ContractMeta;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractMetaRecord extends UpdatableRecordImpl<ContractMetaRecord> implements Record7<String, String, LocalDateTime, Long, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = 145002502;

    /**
     * Setter for <code>rpt.contract_meta.party_id</code>.
     */
    public void setPartyId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.party_id</code>.
     */
    public String getPartyId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>rpt.contract_meta.contract_id</code>.
     */
    public void setContractId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.contract_id</code>.
     */
    public String getContractId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rpt.contract_meta.wtime</code>.
     */
    public void setWtime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.wtime</code>.
     */
    public LocalDateTime getWtime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>rpt.contract_meta.last_event_id</code>.
     */
    public void setLastEventId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.last_event_id</code>.
     */
    public Long getLastEventId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>rpt.contract_meta.schedule_id</code>.
     */
    public void setScheduleId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.schedule_id</code>.
     */
    public Integer getScheduleId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>rpt.contract_meta.calendar_id</code>.
     */
    public void setCalendarId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.calendar_id</code>.
     */
    public Integer getCalendarId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>rpt.contract_meta.last_report_created_at</code>.
     */
    public void setLastReportCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>rpt.contract_meta.last_report_created_at</code>.
     */
    public LocalDateTime getLastReportCreatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, LocalDateTime, Long, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, LocalDateTime, Long, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ContractMeta.CONTRACT_META.PARTY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ContractMeta.CONTRACT_META.CONTRACT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field3() {
        return ContractMeta.CONTRACT_META.WTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return ContractMeta.CONTRACT_META.LAST_EVENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ContractMeta.CONTRACT_META.SCHEDULE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ContractMeta.CONTRACT_META.CALENDAR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return ContractMeta.CONTRACT_META.LAST_REPORT_CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getContractId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value3() {
        return getWtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getLastEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getScheduleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getCalendarId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getLastReportCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value1(String value) {
        setPartyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value2(String value) {
        setContractId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value3(LocalDateTime value) {
        setWtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value4(Long value) {
        setLastEventId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value5(Integer value) {
        setScheduleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value6(Integer value) {
        setCalendarId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord value7(LocalDateTime value) {
        setLastReportCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractMetaRecord values(String value1, String value2, LocalDateTime value3, Long value4, Integer value5, Integer value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContractMetaRecord
     */
    public ContractMetaRecord() {
        super(ContractMeta.CONTRACT_META);
    }

    /**
     * Create a detached, initialised ContractMetaRecord
     */
    public ContractMetaRecord(String partyId, String contractId, LocalDateTime wtime, Long lastEventId, Integer scheduleId, Integer calendarId, LocalDateTime lastReportCreatedAt) {
        super(ContractMeta.CONTRACT_META);

        set(0, partyId);
        set(1, contractId);
        set(2, wtime);
        set(3, lastEventId);
        set(4, scheduleId);
        set(5, calendarId);
        set(6, lastReportCreatedAt);
    }
}
